# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 10:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_at', models.DateTimeField(auto_created=True, null=True)),
                ('checkin_at', models.DateTimeField(auto_created=True, null=True)),
                ('image_objects', models.IntegerField(blank=True, null=True)),
                ('image_status', models.CharField(choices=[('InProcess', 'InProcess'), ('Labelled', 'Labelled'), ('Corrected', 'Corrected'), ('ChangeNeeded', 'ChangeNeeded')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('total_time', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('previous_designation', models.CharField(max_length=100, null=True)),
                ('shift', models.CharField(max_length=100, null=True)),
                ('emp_id', models.IntegerField(default='00000', null=True)),
                ('project', models.CharField(max_length=100, null=True)),
                ('education', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('experience', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='admin', max_length=20)),
                ('updated_by', models.CharField(default='admin', max_length=20)),
                ('designation', models.ForeignKey(default='7', on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200)),
                ('image_type', models.CharField(max_length=150)),
                ('file_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Unlabelled', 'Unlabelled'), ('Labelled', 'Labelled'), ('Corrected', 'Corrected'), ('Completed', 'Completed'), ('Uploaded', 'Uploaded'), ('Approved', 'Approved'), ('ChangeNeeded', 'ChangeNeeded')], default='Unlabelled', max_length=15)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='admin', max_length=20)),
                ('updated_by', models.CharField(default='admin', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_date', models.DateField(auto_created=True, blank=True, null=True)),
                ('completed_date', models.DateField(auto_created=True, blank=True, null=True)),
                ('total_image', models.IntegerField(default='00000', null=True)),
                ('package_name', models.CharField(max_length=200)),
                ('package_date', models.DateField()),
                ('package_status', models.CharField(choices=[('Unlabelled', 'Unlabelled'), ('Label', 'Labelled'), ('Corrected', 'Corrected'), ('Uploaded', 'Uploaded')], default='Unlabelled', max_length=15)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='admin', max_length=20)),
                ('updated_by', models.CharField(default='admin', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('customer', models.CharField(max_length=200)),
                ('project_type', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('resources', models.IntegerField()),
                ('total_image', models.IntegerField()),
                ('current_uploaded', models.IntegerField()),
                ('challenges', models.CharField(max_length=500)),
                ('project_status', models.CharField(choices=[('Current', 'Current'), ('On Hold', 'On Hold'), ('Complete', 'Complete'), ('Planned', 'Planned')], default='Planned', max_length=15)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='admin', max_length=20)),
                ('updated_by', models.CharField(default='admin', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Project'),
        ),
        migrations.AddField(
            model_name='image',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Package'),
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Project'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkout',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Image'),
        ),
    ]
