# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='correction_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='label_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
