# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelling_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('customer', models.CharField(max_length=200)),
                ('project_type', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('resources', models.IntegerField()),
                ('total_image', models.IntegerField()),
                ('current_uploaded', models.IntegerField()),
                ('challanges', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='correction',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='correction',
            name='package_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='package_id',
        ),
        migrations.AddField(
            model_name='correction',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Image'),
        ),
        migrations.AddField(
            model_name='correction',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Package'),
        ),
        migrations.AddField(
            model_name='image',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Package'),
        ),
        migrations.AddField(
            model_name='package',
            name='created_date',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='total_image',
            field=models.IntegerField(default='000', null=True),
        ),
        migrations.AddField(
            model_name='labelling',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Image'),
        ),
        migrations.AddField(
            model_name='labelling',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Package'),
        ),
        migrations.AddField(
            model_name='labelling',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Project'),
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Project'),
        ),
        migrations.AddField(
            model_name='package',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Project'),
        ),
    ]
