# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 06:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracksheet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='image_id',
            new_name='image_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='total_image',
            new_name='total_packages',
        ),
        migrations.AddField(
            model_name='image',
            name='assign_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkin_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='image_objects',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='image_status',
            field=models.CharField(choices=[('InProcess', 'InProcess'), ('Labelled', 'Labelled'), ('Corrected', 'Corrected'), ('ChangeNeeded', 'ChangeNeeded'), ('InQuality', 'InQuality')], max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
