# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0002_auto_20180403_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='corrected_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='label_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
