# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0002_auto_20170914_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correction',
            name='image',
        ),
        migrations.RemoveField(
            model_name='correction',
            name='package',
        ),
        migrations.RemoveField(
            model_name='labelling',
            name='image',
        ),
        migrations.RemoveField(
            model_name='labelling',
            name='package',
        ),
        migrations.RemoveField(
            model_name='labelling',
            name='project',
        ),
        migrations.AddField(
            model_name='image',
            name='image_status',
            field=models.CharField(choices=[('Unlabelled', 'Unlabelled'), ('Label', 'Labelled'), ('Corrected', 'Corrected'), ('Uploaded', 'Uploaded')], default='Unlabelled', max_length=15),
        ),
        migrations.AddField(
            model_name='package',
            name='package_status',
            field=models.CharField(choices=[('Unlabelled', 'Unlabelled'), ('Paused', 'Paused'), ('Labelled', 'Labelled'), ('Corrected', 'Corrected'), ('Completed', 'Completed'), ('Uploaded', 'Uploaded')], default='Unlabelled', max_length=15),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('Current', 'Current'), ('On Hold', 'On Hold'), ('Complete', 'Complete'), ('Planned', 'Planned')], default='Planned', max_length=15),
        ),
        migrations.DeleteModel(
            name='Correction',
        ),
        migrations.DeleteModel(
            name='Labelling',
        ),
    ]
