# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0002_auto_20171108_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'permissions': (('view_package', 'Can view package'),)},
        ),
    ]
