# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0003_auto_20171108_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('view_projects', 'Can view projects'),)},
        ),
    ]
