# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 12:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracksheet', '0003_auto_20170914_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=100)),
                ('emp_id', models.IntegerField(default='000', null=True)),
                ('project', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
