# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracksheet', '0003_auto_20180405_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='corrected_by',
        ),
        migrations.RemoveField(
            model_name='image',
            name='label_by',
        ),
        migrations.AddField(
            model_name='checkout',
            name='correct_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkout',
            name='label_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
