# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0004_auto_20171108_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('view_employees', 'Can view employees'),)},
        ),
    ]
