# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0005_auto_20171108_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='correction_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='label_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='loop_on_image',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='image_status',
            field=models.CharField(choices=[('InProcess', 'InProcess'), ('Labelled', 'Labelled'), ('Corrected', 'Corrected'), ('ChangeNeeded', 'ChangeNeeded'), ('InQuality', 'InQuality'), ('Approved', 'Approved')], max_length=15),
        ),
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('Unlabelled', 'Unlabelled'), ('InProcess', 'InProcess'), ('Labelled', 'Labelled'), ('Corrected', 'Corrected'), ('ChangeNeeded', 'ChangeNeeded'), ('InQuality', 'InQuality'), ('Approved', 'Approved'), ('Uploaded', 'Uploaded')], default='Unlabelled', max_length=15),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_status',
            field=models.CharField(choices=[('Unlabelled', 'Unlabelled'), ('InProcess', 'InProcess'), ('Completed', 'Completed'), ('Uploaded', 'Uploaded')], default='Unlabelled', max_length=15),
        ),
    ]
