# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0005_auto_20180405_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='approved_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='approved_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='corrected_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='label_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
