# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-11 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0006_auto_20180406_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-id'], 'permissions': (('view_image', 'Can view image'),)},
        ),
    ]
