# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0006_auto_20171101_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='image_id',
            new_name='image_name',
        ),
    ]
