# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0006_auto_20171109_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='loop_on_image',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
