# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0006_auto_20170922_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='previous_designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
