# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracksheet', '0007_auto_20170922_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='correction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='correction_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='correction_time_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_objects',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='label_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='labeldate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='labelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='labeltime',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='package',
            name='completed_date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='uploaded_date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(default='7', on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
