# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-12 06:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracksheet', '0007_auto_20180411_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='bicycle_group',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='day_lights',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Night', 'Night'), ('Twilight', 'Twilight')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='motorbike_group',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='no_of_bicycle',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='no_of_mistakes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='no_of_motorbike',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='no_of_scooters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='occlusion_truncation_issues',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='other_tag_issues',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='scene_type',
            field=models.CharField(blank=True, choices=[('Country Road', 'Country Road'), ('Highway', 'Highway'), ('City', 'City')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='scooter_group',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='total_unique_bicycle',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='total_unique_motorbike',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='total_unique_objects',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='total_unique_scooter',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='weather',
            field=models.CharField(blank=True, choices=[('Clear', 'Clear'), ('Cloudy', 'Cloudy'), ('Rainy', 'Rainy')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_checked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='border_issues',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='image_status',
            field=models.CharField(choices=[('InProcess', 'InProcess'), ('Labelled', 'Labelled'), ('Corrected', 'Corrected'), ('ChangeNeeded', 'ChangeNeeded'), ('InQuality', 'InQuality'), ('InChecking', 'InChecking'), ('Checked', 'Checked'), ('Practice', 'Practice'), ('Approved', 'Approved')], max_length=15),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='layer_issues',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='missing_objects',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='folder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='total_image',
            field=models.PositiveIntegerField(default='00000', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_assign_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='package',
            name='total_image',
            field=models.PositiveIntegerField(default='00000', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='challenges',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_uploaded',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='resources',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_packages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sequence_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='total_image',
            field=models.PositiveIntegerField(default='00000', null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='set_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='total_image',
            field=models.PositiveIntegerField(default='00000', null=True),
        ),
    ]
