# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0007_auto_20171109_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
