# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0008_auto_20171113_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime, null=True),
        ),
    ]
