# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0009_auto_20171113_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
