# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0009_auto_20171001_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='package',
            name='package_date',
            field=models.DateField(),
        ),
    ]
