# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-19 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0009_auto_20180419_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Set'),
        ),
    ]
