# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0010_auto_20171113_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
