# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0010_auto_20180419_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='border_issues',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='layer_issues',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='missing_objects',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='total_objects',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
