# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0011_auto_20171113_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
