# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0011_auto_20171010_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
