# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-04 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0012_auto_20180420_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='created_by',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='folder',
            name='updated_by',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='created_by',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='updated_by',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_by',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='created_by',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='updated_by',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='set',
            name='created_by',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='set',
            name='updated_by',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
