# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0012_auto_20171010_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='time_on_image',
        ),
        migrations.AddField(
            model_name='checkout',
            name='checkin_at',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='total_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_at',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
