# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0012_auto_20171114_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_type',
            field=models.CharField(choices=[('png', 'png'), ('pgm', 'pgm'), ('ppm', 'ppm')], default='png', max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.CharField(choices=[('hard', 'hard'), ('easy', 'easy'), ('medium', 'medium')], default='hard', max_length=150, null=True),
        ),
    ]
