# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0013_auto_20171012_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkin_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
