# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 09:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0013_auto_20171116_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
