# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-05 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0014_package_package_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set([('package_name', 'project')]),
        ),
    ]
