# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0015_auto_20171121_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='set_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
