# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0015_auto_20171013_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('Unlabelled', 'Unlabelled'), ('Labelled', 'Labelled'), ('Corrected', 'Corrected'), ('Completed', 'Completed'), ('Uploaded', 'Uploaded'), ('Approved', 'Approved'), ('ChangeNeeded', 'ChangeNeeded')], default='Unlabelled', max_length=15),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='image_status',
            field=models.CharField(blank=True, choices=[('InProcess', 'InProcess'), ('Labelled', 'Labelled'), ('Corrected', 'Corrected'), ('ChangeNeeded', 'ChangeNeeded')], max_length=15),
        ),
    ]
