# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0016_image_set_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_date', models.DateField(auto_created=True, blank=True, null=True)),
                ('completed_date', models.DateField(auto_created=True, blank=True, null=True)),
                ('total_image', models.IntegerField(default='00000', null=True)),
                ('folder_name', models.CharField(max_length=200)),
                ('folder_date', models.DateField()),
                ('folder_status', models.CharField(choices=[('Unlabelled', 'Unlabelled'), ('InProcess', 'InProcess'), ('Completed', 'Completed'), ('Uploaded', 'Uploaded')], default='Unlabelled', max_length=15)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='admin', max_length=20)),
                ('updated_by', models.CharField(default='admin', max_length=20)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Package')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Project')),
            ],
            options={
                'permissions': (('view_folder', 'Can view folder'),),
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_date', models.DateField(auto_created=True, blank=True, null=True)),
                ('completed_date', models.DateField(auto_created=True, blank=True, null=True)),
                ('total_image', models.IntegerField(default='00000', null=True)),
                ('sequence_name', models.CharField(max_length=200)),
                ('sequence_date', models.DateField()),
                ('sequence_status', models.CharField(choices=[('Unlabelled', 'Unlabelled'), ('InProcess', 'InProcess'), ('Completed', 'Completed'), ('Uploaded', 'Uploaded')], default='Unlabelled', max_length=15)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='admin', max_length=20)),
                ('updated_by', models.CharField(default='admin', max_length=20)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Package')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Project')),
            ],
            options={
                'permissions': (('view_sequence', 'Can view sequence'),),
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_date', models.DateField(auto_created=True, blank=True, null=True)),
                ('completed_date', models.DateField(auto_created=True, blank=True, null=True)),
                ('total_image', models.IntegerField(default='00000', null=True)),
                ('set_name', models.CharField(max_length=200)),
                ('set_date', models.DateField()),
                ('set_status', models.CharField(choices=[('Unlabelled', 'Unlabelled'), ('InProcess', 'InProcess'), ('Completed', 'Completed'), ('Uploaded', 'Uploaded')], default='Unlabelled', max_length=15)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='admin', max_length=20)),
                ('updated_by', models.CharField(default='admin', max_length=20)),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Folder')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Package')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Project')),
                ('sequence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Sequence')),
            ],
            options={
                'permissions': (('view_set', 'Can view set'),),
            },
        ),
        migrations.RemoveField(
            model_name='image',
            name='folder_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='sequence_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='set_name',
        ),
        migrations.AddField(
            model_name='folder',
            name='sequence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Sequence'),
        ),
        migrations.AddField(
            model_name='image',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Folder'),
        ),
        migrations.AddField(
            model_name='image',
            name='sequence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Sequence'),
        ),
        migrations.AddField(
            model_name='image',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Set'),
        ),
    ]
