# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0020_auto_20171122_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='image_id',
            new_name='image',
        ),
    ]
