# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0021_auto_20171124_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='sequence',
        ),
        migrations.AddField(
            model_name='sequence',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracksheet.Folder'),
        ),
    ]
