# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracksheet', '0022_auto_20171208_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
