"""
Django settings for trackdata project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9d7p9=@5g9f)w2yf2hdriur*earzjxyi6plz7xx3(miwkrlamc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ["*",]

#INTERNAL_IPS = ["localhost"]
# Application definition

INSTALLED_APPS = [
    'tracksheet.apps.TracksheetConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles',
    'django_filters',
    'bootstrap3',
    'django_tables2',
    'django_tables2_column_shifter',
    'crispy_forms',
    'import_export',
    'datetimewidget',
    'initial_avatars',
    'bulk_admin',
    'django_messages',
    'compressor',
    'django_admin_listfilter_dropdown',
]

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',

]

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # other finders..
    'compressor.finders.CompressorFinder',
)


ROOT_URLCONF = 'trackdata.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR +'/templates',
            BASE_DIR +'/templates/registration',
            BASE_DIR +'/templates/tracksheet',
            BASE_DIR +'/templates/tracksheet/messages',
            BASE_DIR +'/templates/tracksheet/notification',

        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_messages.context_processors.inbox',
            ],
        },
    },
]

WSGI_APPLICATION = 'trackdata.wsgi.application'




# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'trackpro',
        'PASSWORD': 'Password@123',
        'USER': 'pc84',
        'HOST': 'localhost',
        'PORT' : '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE =  'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SITE_ID = 2
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')
STATIC_URL = '/static/'
DATA_UPLOAD_MAX_NUMBER_FIELDS = 21000

COMPRESS_ENABLED = True
COMPRESS_OFFLINE = True
COMPRESS_PARSER = 'compressor.parser.LxmlParser'
# COMPRESS_CSS_FILTERS = [
#     'compressor.filters.css_default.CssAbsoluteFilter',
#     'compressor.filters.cssmin.CSSMinFilter',
#     ]
# COMPRESS_JS_FILTERS = [
#     'compressor.filters.closure.ClosureCompilerFilter',
# ]

#COMPRESS_CLOSURE_COMPILER_BINARY = 'java -jar /path/to/compiler.jar'



LOGIN_REDIRECT_URL = '/tracksheet/'
LOGOUT_REDIRECT_URL = '/'
#CRISPY_TEMPLATE_PACK = 'uni_form'
#
MEDIA_ROOT = os.path.join(BASE_DIR,'MEDIA')
MEDIA_URL='/media/'
# # AVATAR_STORAGE_BACKEND = 'trackdata.custom_storages.AvatarStorage'
#AVATAR_STORAGE_FOLDER = BASE_DIR + '/tracksheet/avatars'
#AVATAR_DEFAULT_SHAPE = 'square'
AVATAR_HIGH_RESOLUTION = True
AVATAR_COLORS = ((0,0, 0), (0, 0, 0),)
GRAVATAR_DEFAULT_SIZE = 200



#Email Configuration

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_HOST = 'smtp.office365.com'
# EMAIL_HOST_USER = ''
# EMAIL_HOST_PASSWORD = 'AEaur#1010'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# DEFAULT_FROM_EMAIL = 'akshaye@ec-mobility.biz'
# SERVER_EMAIL = 'akshaye@ec-mobility.biz'
#ENCRIPTION_: STARTTLS
# EMAIL_USE_TLS = True
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST_USER = 'akkierande@gmail.com'
# EMAIL_HOST_PASSWORD = 'Prem7736'
# EMAIL_PORT = 587